### ISSUE TITLE
can't run the demo

### ISSUE THREAD

**Issue by laminsk** [danbrough/andrudio#1]
Hi there

I'm trying to run the demo in android studio and getting this error message. Any ideas :)

05-11 10:31:15.494  27702-27702/? D/dalvikvm﹕ Late-enabling CheckJNI
05-11 10:31:15.584  27702-27702/danbroid.andrudio.demo W/dalvikvm﹕ Exception Ljava/lang/UnsatisfiedLinkError; thrown while initializing Ldanbroid/andrudio/demo/MainActivity;
05-11 10:31:15.584  27702-27702/danbroid.andrudio.demo W/dalvikvm﹕ Class init failed in newInstance call (Ldanbroid/andrudio/demo/MainActivity;)
05-11 10:31:15.584  27702-27702/danbroid.andrudio.demo D/AndroidRuntime﹕ Shutting down VM
05-11 10:31:15.584  27702-27702/danbroid.andrudio.demo W/dalvikvm﹕ threadid=1: thread exiting with uncaught exception (group=0x41f2aba8)
05-11 10:31:15.584  27702-27702/danbroid.andrudio.demo E/AndroidRuntime﹕ FATAL EXCEPTION: main
    Process: danbroid.andrudio.demo, PID: 27702
    java.lang.UnsatisfiedLinkError: Couldn't load avutil from loader dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/danbroid.andrudio.demo-2.apk"],nativeLibraryDirectories=[/data/app-lib/danbroid.andrudio.demo-2, /vendor/lib, /system/lib]]]: findLibrary returned null
            at java.lang.Runtime.loadLibrary(Runtime.java:358)
            at java.lang.System.loadLibrary(System.java:526)
            at danbroid.andrudio.LibAndrudio.initialize(LibAndrudio.java:39)
            at danbroid.andrudio.demo.MainActivity.<clinit>(MainActivity.java:26)
            at java.lang.Class.newInstanceImpl(Native Method)
            at java.lang.Class.newInstance(Class.java:1208)
            at android.app.Instrumentation.newActivity(Instrumentation.java:1061)
            at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2112)
            at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2245)
            at android.app.ActivityThread.access$800(ActivityThread.java:135)
            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1196)
            at android.os.Handler.dispatchMessage(Handler.java:102)
            at android.os.Looper.loop(Looper.java:136)
            at android.app.ActivityThread.main(ActivityThread.java:5017)
            at java.lang.reflect.Method.invokeNative(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:515)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:779)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:595)

**Comment by laminsk** [comment]
Finally figured it out, got it running now.

**Comment by danbrough** [comment]
Sorry, missed that. Must sort out my notification settings.
